/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProcessoRouteImport } from './routes/processo'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoRoute = ProcessoRouteImport.update({
  id: '/processo',
  path: '/processo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/notas': typeof NotasRoute
  '/playground': typeof PlaygroundRoute
  '/processo': typeof ProcessoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/notas': typeof NotasRoute
  '/playground': typeof PlaygroundRoute
  '/processo': typeof ProcessoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/notas': typeof NotasRoute
  '/playground': typeof PlaygroundRoute
  '/processo': typeof ProcessoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/notas'
    | '/playground'
    | '/processo'
    | '/servicos'
    | '/sobre'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/notas'
    | '/playground'
    | '/processo'
    | '/servicos'
    | '/sobre'
    | '/projetos/$slug'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/notas'
    | '/playground'
    | '/processo'
    | '/servicos'
    | '/sobre'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  NotasRoute: typeof NotasRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProcessoRoute: typeof ProcessoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo': {
      id: '/processo'
      path: '/processo'
      fullPath: '/processo'
      preLoaderRoute: typeof ProcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  NotasRoute: NotasRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProcessoRoute: ProcessoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
